version: '3.8'

services:
  nginx-proxy:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl # Thư mục chứa chứng chỉ SSL
      - ./nginx/conf.d:/etc/nginx/conf.d # Các file cấu hình bổ sung
    restart: always
    networks:
      - my_network

  bannoithat-user:
    image: tuananh21225/bannoithat-user
    container_name: bannoithat-user
    restart: always
    networks:
      - my_network

  ownweb-ar:
    image: tuananh21225/bannoithat-ar
    container_name: ownweb-ar
    restart: always
    networks:
      - my_network

  bannoithat-api:
    image: tuananh21225/bannoithat-api
    container_name: bannoithat-api
    ports:
      - 7000:7000
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:7000
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
