services:
  bannoithat-api:
    image: tuananh21225/bannoithat-api
    ports:
      - 7000:7000
      - 8000:8000
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:7000;http://+:8000
      - ASPNETCORE_Kestrel__Certificates__Default__Password=bannoithat
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    volumes:
      - ~/.aspnet/https:/https:ro